#ifndef _PGUPV_H 
#define _PGUPV_H 2011

#include "app.h"
#include "renderer.h"
#include "viewportRenderer.h"
#include "uboLightSources.h"
#include "uboPBRLightSources.h"
#include "stockModels.h"
#include "stockModels2.h"
#include "stockMaterials.h"
#include "stockPrograms.h"
#include "fileLoader.h"
#include "program.h"
#include "window.h"
#include "fbo.h"
#include "texture1D.h"
#include "texture2D.h"
#include "textureRectangle.h"
#include "textureCubeMap.h"
#include "texture2DArray.h"
#include "textureText.h"
#include "textureVideo.h"
#include "bufferTexture.h"
#include "log.h"
#include "interpolators.h"
#include "indexedBindingPoint.h"
#include "font.h"
#include "image.h"
#include "hacks.h"
#include "image.h"
#include "keyboard.h"
#include "query.h"
#include "glStateCache.h"
#include "commandLineProcessor.h"
#include "drawCommand.h"
#include "texture2DBlitter.h"
#include "material.h"
#include "pbrMaterial.h"
#include "uboPBRMaterial.h"
#include "picker.h"

// Animación
#include "animationClip.h"
#include "animationChannel.h"
#include "skeleton.h"
#include "bone.h"
#include "uboBones.h"

// Grafos de escena
#include "node.h"
#include "transform.h"
#include "group.h"
#include "geode.h"
#include "scene.h"
#include "nodeVisitor.h"

#endif
