
IF(APPLE) 
FIND_PATH(ASSIMP_INCLUDE_DIR assimp/postprocess.h)
FIND_PATH(ASSIMP_INCLUDE_DIR assimp/scene.h)
FIND_PATH(SDL2_INCLUDE_DIR SDL2/SDL.h)
FIND_PATH(SDL2_TTF_INCLUDE_DIR SDL_ttf.h)
INCLUDE_DIRECTORIES(${SDL2_INCLUDE_DIR} ${SDL2_TTF_INCLUDE_DIR} ${ASSIMP_INCLUDE_DIR})
ELSE(APPLE)
INCLUDE_DIRECTORIES("/usr/include/SDL2")
ENDIF(APPLE)

INCLUDE_DIRECTORIES(${PG_SOURCE_DIR}/librerias/boost ${PG_SOURCE_DIR}/PGUPV/include ${PG_SOURCE_DIR}/librerias/glm ${PG_SOURCE_DIR}/librerias/glew/include ${PG_SOURCE_DIR}/librerias/dearimgui/include ${PG_SOURCE_DIR}/librerias/GSL/include)

if(CMAKE_COMPILER_IS_GNUCXX)
  set(CMAKE_CXX_FLAGS "-O2 -std=c++0x -Wall")
endif()


